# Generated by Django 4.0.1 on 2022-02-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='avater',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='password1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Пароль1'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='password2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Пароль2'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='аватар'),
        ),
    ]
